options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
steps:
  - name: 'docker/compose:1.29.2'
    args: ['-f', 'compose.yaml', 'build']
  - name: 'docker/compose:1.29.2'
    args: ['-f', 'compose.yaml', 'push']

images:
  - 'gcr.io/$PROJECT_ID/identityservice:latest'
  - 'gcr.io/$PROJECT_ID/customerservice:latest'
  - 'gcr.io/$PROJECT_ID/claimprocessingservice:latest'  