options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
steps:
  # Build and Push the Docker image
  - name: 'docker/compose:1.29.2'
    args: ['-f', 'compose.yaml', 'build']
  - name: 'docker/compose:1.29.2'
    args: ['-f', 'compose.yaml', 'push']

  # Deploy the Docker image to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
            'run', 'deploy', 'identityservice', 
            '--image', 'gcr.io/$PROJECT_ID/identityservice:latest', 
            '--region', 'us-central1',
            '--allow-unauthenticated',
            '--set-env-vars', 'PORT=5001']
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
            'run', 'deploy', 'customerservice', 
            '--image', 'gcr.io/$PROJECT_ID/customerservice:latest', 
            '--region', 'us-central1',
            '--allow-unauthenticated',
            '--set-env-vars', 'PORT=5002']
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
               'run', 'deploy', 'claimprocessingservice', 
               '--image', 'gcr.io/$PROJECT_ID/claimprocessingservice:latest', 
               '--region', 'us-central1',
               '--allow-unauthenticated',
                '--set-env-vars', 'PORT=5003'] 


   # Add IAM policy binding
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      [
        'beta', 'run', 'services', 'add-iam-policy-binding', 'identityservice',
        '--region=us-central1',
        '--member=allUsers',
        '--role=roles/run.invoker'
      ]

images:
  - 'gcr.io/$PROJECT_ID/identityservice:latest'
  - 'gcr.io/$PROJECT_ID/customerservice:latest'
  - 'gcr.io/$PROJECT_ID/claimprocessingservice:latest' 


