services:
  identityservice:
    build:
      context: . 
      dockerfile: IdentityService.API/Dockerfile # Path to the IdentityService Dockerfile
    image: gcr.io/$PROJECT_ID/identityservice
    ports:
      - "5001:5001"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__EInsuranceIdentityConnectionString=Host=postgres;Port=5432;Database=Identity;Username=postgres;Password=password
    depends_on:
      - postgres
    networks:
      - backend

  customerservice:
    build:
      context: .
      dockerfile: CustomerService.API/Dockerfile   # Path to the CustomerService Dockerfile
    image: gcr.io/$PROJECT_ID/customerservice
    ports:
      - "5002:5002"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__CustomerServiceConnectionString=Host=postgres;Port=5432;Database=Customers;Username=postgres;Password=password
    depends_on:
      - postgres
      - identityservice
    networks:
      - backend

  claimprocessingservice:
    build:
      context: .
      dockerfile: ClaimProcessingService.API/Dockerfile # Path to the ClaimProcessingService Dockerfile
    image: gcr.io/$PROJECT_ID/claimprocessingservice
    ports:
      - "5003:5003"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__ClaimProcessingServiceConnectionString=Host=postgres;Port=5432;Database=ClaimProcessing;Username=postgres;Password=password
    depends_on:
      - postgres
      - identityservice
    networks:
      - backend

  postgres:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - backend
   
volumes:
  pgdata:

networks:
  backend: