apiVersion: v1                      # API version for Service.
kind: Service                       # Specifies this object is a Service.
metadata:
  name: identityservice-api           # Name of the service.
  labels:                           # Labels to organize and select the service.
    app: identityservice-api         # Label for categorizing this service.

spec:
  selector:                         # Defines which Pods this service will route traffic to.
    app: identityservice-api         # Matches the Pods that have this label.
  type: NodePort                   # Type of service (ClusterIP, NodePort, LoadBalancer, ExternalName).
  ports:                            # Defines the ports the service will expose.
  - protocol: TCP                   # Protocol for the service (usually TCP).
    port: 5001                      # Port on which the service will be accessible.
    targetPort: 5001                # Port on the Pod that the service forwards to.
    nodePort: 30000
  

---

apiVersion: apps/v1               # API version for Deployment. The `apps/v1` is the latest stable version for Deployments.
kind: Deployment                  # Specifies that this is a Deployment object.
metadata:
  name: identityservice-api       # Name of the deployment.
  labels:                         # Labels to organize and select objects.
    app: identityservice-api      # Label key-value pair for this deployment.

spec:
  selector:
    matchLabels:                  # Selector ensures the deployment manages Pods with these labels.
      app: identityservice-api 
  template:                      
    metadata:
      labels:
        app: identityservice-api     # Labels that match the selector for the deployment.
    spec:
      containers:
      - name: identityservice            # Name of the container within the pod.
        image: sushmasao353/eclaiminsuranceprocessing-identityservice         # The container image to run.
        

